config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/about' => 'homes#about'
  scope module: :public do
    resources :items, only: [:index,:show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index,:create,:update,:destroy]
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update] do
      resources :order_details, only: [:update]
    end
  end

  devise_for :admin, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    confirmations: "customers/confirmations"
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :phone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     customers_mypage_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def create
    super do |resource|
      resource.is_active = true 
      resource.save
    end
  end
  
  
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4" style="background-color: #DCC2A1; margin-top: 40px;">
      <h4 class="text-center"><strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</strong></h4>
    </div>
  </div>
  <%= form_with model: [:admin, @customer] do |f| %>
  <table class="table table-borderless">
    <tr>
      <th style="border-top: Transparent; border-bottom: 1px solid Transparent;">会員ID</th>
      <td style="border-top: Transparent; border-bottom: 1px solid Transparent;"><%= @customer.id %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">氏名</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">フリガナ</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">郵便番号</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">住所</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :address %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">電話番号</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :phone_number %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">メールアドレス</th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;">会員ステータス</th>
      <td style="border-bottom: 1px solid Transparent;">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効", {value: :true} %>

        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "退会", {value: :false} %>
      </td>
    </tr>
    <tr>
      <th style="border-bottom: 1px solid Transparent;"></th>
      <td style="border-bottom: 1px solid Transparent;"><%= f.submit "変更を保存", class:"btn btn-success" %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4" style="background-color: #DCC2A1; margin-top: 40px;">
      <h4 class="text-center"><strong>会員一覧</strong></h4>
    </div>
  </div>
  <table class='table' style="margin-top: 30px;">
    <thead style="background-color: #DCC2A1;">
      <tr>
        <th style="border-bottom: 1px solid Transparent;">会員ID</th>
        <th style="border-bottom: 1px solid Transparent;">氏名</th>
        <th style="border-bottom: 1px solid Transparent;">メールアドレス</th>
        <th style="border-bottom: 1px solid Transparent;">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id), style: "color: black; text-decoration: underline;" do %>
              <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td><%= customer.customer_status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4" style="background-color: #DCC2A1; margin-top: 40px;">
      <h4 class="text-center"><strong><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</strong></h4>
    </div>
  </div>
  <div class="d-flex align-items-center">
    <table class="table table-borderless">
      <tr>
        <th style="border-top: Transparent;">会員ID</th>
        <td style="border-top: Transparent;"><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td><%= @customer.customer_status %></td>
      </tr>

      <tr>
        <th style="border-bottom: 1px solid Transparent;"></th>
        <td style="border-bottom: 1px solid Transparent;">
          <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
          <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary" %>
        </td>
      </tr>
    </table>
  </div>
</div>