config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/about' => 'homes#about'
  scope module: :public do
    resources :items, only: [:index,:show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index,:create,:update,:destroy]
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update] do
      resources :order_details, only: [:update]
    end
  end

  devise_for :admin, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    confirmations: "customers/confirmations"
  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: {
    credit_card: 0,
    transfer: 1
  }

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

  after_update :update_making_status, if: :saved_change_to_status?

  private

  def update_making_status
    if status == "入金確認"
      order_details.update_all(making_status: :製作待ち)
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_order, only: [:index,:show, :update]
  
  def index
    @params = params[:id]
    @order = Order.where(customer_id: @params).page(params[:page]).per(10).order(created_at: :desc)
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @order_details = @order.order_details.includes(:item)
  end

  def update
    if @order.update(order_params)
      flash[:status_success] = '注文ステータスが更新されました。'
      redirect_to admin_order_path(@order)
    else
      flash[:status_error] = '注文ステータスの更新に失敗しました。'
      render :show
    end
  end

  private

  def set_order
    @order = Order.find_by(id: params[:id])
  end
    
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4" style="background-color: #DCC2A1; margin-top: 40px;">
      <h4 class="text-center"><strong>注文履歴一覧</strong></h4>
    </div>
  </div>
  
  <table class="table" style="margin-top: 30px;">
    <thead style="background-color: #DCC2A1;">
      <tr>
        <th style="border-bottom: 2px solid #C3A78F;">購入日時</th>
        <th style="border-bottom: 2px solid #C3A78F;">購入者</th>
        <th style="border-bottom: 2px solid #C3A78F;">注文個数</th>
        <th style="border-bottom: 2px solid #C3A78F;">注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"), admin_order_path(order), style: "color: black; text-decoration: underline; color: black;" %>
          </td>
          <td>
            <%= order.customer.last_name+order.customer.first_name %>
          </td>
          <td>
            <% @total_amount = 0 %>
            <% order.order_details.each do |order_detail| %>
            <% @total_amount += order_detail.amount %>
            <% end %>
            <%= @total_amount %>
          </td>
          <td><%= order.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4" style="background-color: #DCC2A1; margin-top: 40px;">
      <h4 class="text-center"><strong>注文履歴詳細</strong></h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-5" style="margin:10px 0 -20px -15px;">
    <% if flash[:status_success] %>
      <div class="alert alert-success">
        <%= flash[:status_success] %>
      </div>
    <% end %>
    <% if flash[:status_error] %>
      <div class="alert alert-danger">
        <%= flash[:status_error] %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="row" style="margin: 20px 0;">
    <div class="col-md-8">
      <div class="mb-3 pb-3" style="border-bottom: 1px solid #C3A78F;">
        <div class="d-inline-block" style="width: 150px;"><strong>購入者</strong></div>
        <div class="d-inline-block">
          <%= link_to "#{ @order.customer.last_name }#{ @order.customer.first_name }",edit_admin_customer_path(@order.customer),style: "text-decoration: underline; color: black;" %>
        </div>
      </div>
  
      <div class="mb-3 pb-3" style="border-bottom: 1px solid #C3A78F;">
        <div class="d-inline-block" style="width: 150px;"><strong>注文日</strong></div>
        <div class="d-inline-block"><%= @order.created_at.strftime("%Y/%m/%d") %></div>
      </div>
  
      <div class="mb-3 pb-3" style="border-bottom: 1px solid #C3A78F;">
        <div class="d-inline-block" style="width: 150px;"><strong>配送先</strong></div>
        <div class="d-inline-block"><%= @order.address %></div>
      </div>
  
      <div class="mb-3 pb-3" style="border-bottom: 1px solid #C3A78F;">
        <div class="d-inline-block" style="width: 150px;"><strong>支払方法</strong></div>
        <div class="d-inline-block"><%= t("enums.order.payment_method.#{@order.payment_method}") %></div>
      </div>
  
      <div class="mb-3 pb-3" style="border-bottom: 1px solid #C3A78F;">
        <div class="d-inline-block" style="width: 150px;"><strong>注文ステータス</strong></div>
        <div class="d-inline-block">
          <%= form_with(model: @order, url: admin_order_path(@order), method: :patch) do |f| %>
            <%= f.select :status, Order.statuses.map { |status, _value| [status.to_s.humanize, status] },
              prompt: "ステータスを選択してください", class: "form-control mb-2" %>
            <%= f.submit "更新", class: "btn btn-primary"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-6" style="background-color: #DCC2A1; margin-bottom: 25px;">
          <h4 class="text-center"><strong>商品詳細</strong></h4>
        </div>
      </div>
      
      <div class="row">
        <div class="col-8" style="margin:-15px 0 -5px -15px;">
        <% if flash[:making_status_success] %>
          <div class="alert alert-success">
            <%= flash[:making_status_success] %>
          </div>
        <% end %>
        <% if flash[:making_status_error] %>
          <div class="alert alert-danger">
            <%= flash[:making_status_error] %>
          </div>
        <% end %>
        </div>
      </div>
      
      <table class="table" style="border: 1px solid #C3A78F;">
        <thead class="table-title" style="background-color: #DCC2A1;">
          <tr>
            <th style="border-bottom: 1px solid #C3A78F;">商品名</th>
            <th style="border-bottom: 1px solid #C3A78F;">単価（税込）</th>
            <th style="border-bottom: 1px solid #C3A78F;">数量</th>
            <th style="border-bottom: 1px solid #C3A78F;">小計</th>
            <th style="border-bottom: 1px solid #C3A78F;">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td>￥<%= number_with_delimiter((order_detail.item.price * 1.1).round) %></td>
              <td><%= order_detail.amount %></td>
              <td>￥<%= number_with_delimiter(((order_detail.item.price * 1.1) * order_detail.amount).round) %></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_order_detail_path(@order, order_detail),
                  method: :patch) do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.map { |status, _value|
                    [status.to_s.humanize, status] }, prompt: "製作ステータスを選択してください", class: "form-control" %>
                  <%= f.submit "更新", class: "btn btn-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4" style="margin-top: 40px;">
      <div class="row" style="margin: 20px 0;">
        <div class="col-md-9">
          <div class="mb-3 pb-2" style="border-bottom: 1px solid #C3A78F">
            <div class="d-inline-block" style="width: 150px;"><strong>商品合計</strong></div>
            <div class="d-inline-block">￥<%= number_with_delimiter(@order.total_price - @order.shipping_fee) %></div>
          </div>
      
          <div class="mb-3 pb-2" style="border-bottom: 1px solid #C3A78F">
            <div class="d-inline-block" style="width: 150px;"><strong>送料</strong></div>
            <div class="d-inline-block">￥<%= number_with_delimiter(@order.shipping_fee) %></div>
          </div>
      
          <div class="mb-3 pb-2" style="border-bottom: 1px solid #C3A78F;">
            <div class="d-inline-block" style="width: 150px;"><strong>請求金額合計</strong></div>
            <div class="d-inline-block"><strong>￥<%= number_with_delimiter(@order.total_price) %></strong></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>