config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get '/about' => 'homes#about'
  scope module: :public do
    resources :items, only: [:index,:show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index,:create,:update,:destroy]
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new,:create,:index,:show]
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  namespace :admin do
    resources :items, only: [:new,:index,:show,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:index,:show,:edit,:update]
    resources :orders, only: [:index,:show,:update] do
      resources :order_details, only: [:update]
    end
  end

  devise_for :admin, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    confirmations: "customers/confirmations"
  }
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer

    def address_display
      postal_code_str = postal_code.present? ? postal_code : ''
      address_str = address.present? ? address : ''
      name_str = name.present? ? name : ''

      '〒' + postal_code_str + ' ' + address_str + '　' + name_str + '　　'
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
  validates :customer_id, :item_id, :amount, presence: true
    
  def subtotal
    item.with_taxin_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image
  validates :image, :name, :introduction, :price, :genre_id, presence: true
  validates :is_active, inclusion: { in: [true, false] }
  
  def get_image
    image
  end
  
  def with_taxin_price
        price*1.1
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: {
    credit_card: 0,
    transfer: 1
  }

  enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

  after_update :update_making_status, if: :saved_change_to_status?

  private

  def update_making_status
    if status == "入金確認"
      order_details.update_all(making_status: :製作待ち)
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    制作不可: 0,
    製作待ち: 1,
    製作中: 2,
    製作完了: 3
  }

  after_update :update_order_status, if: :saved_change_to_making_status?

  private

  def update_order_status
    if making_status == "製作中"
      order.update(status: :製作中)
    elsif making_status == "製作完了" && order.order_details.all? { |detail| detail.making_status == "製作完了" }
      order.update(status: :発送準備中)
    end
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "ジャンルが作成されました。"
      redirect_to admin_genres_path
    else
      flash.now[:error] = "ジャンルが作成できませんでした。"
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンル名が更新されました。"
      redirect_to admin_genres_path
    else
      flash.now[:error] = "ジャンル名を入力してください。"
      @genre = Genre.find(params[:id])
      render 'edit'
    end
  end
  
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show]
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end
  
  def index
    @items = Item.all
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  
  private
  
  def set_item
    @item = Item.find(params[:id])
  end
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url
  before_action :configure_permitted_parameters, if: :devise_controller?

  def admin_url
    request.fullpath.include?("/admin")
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      root_path
    else
      items_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number,])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @new_items = Item.where(is_active: true).order(created_at: :desc).limit(4)
    # where(is_active: true)で販売中の商品のみ取得、order(created_at: :desc).limit(4)で最新の４件まで取得
  end

  def about
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5><%= pluralize(obj.errors.count, "箇所") %>空欄もしくは選択されていません。</h5>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<h4><strong>🍗 TEAM .H 🍗</strong></h4>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-back" style="height: 7rem;">
  <div class="container-fluid">

    <strong><%= link_to "NAGANOCAKE.", root_path, class: "btn btn-logo"%></strong>
    <div style="margin-left: 450px; font-weight: bold; color: white; font-size: 1.5rem;">
      <% if customer_signed_in? && current_customer %>
        <div>【 ようこそ<span><%= current_customer.last_name + current_customer.first_name %></span>様！ 】</div>
      <% elsif admin_signed_in? %>
        <div>【 管理者用ページ 】</div>
      <% else %>
        <div>【 ようこそゲスト様！ 】</div>
      <% end %>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <% if admin_signed_in? %>
          <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline mx-1" %></li>
        <% elsif customer_signed_in? %>
          <li class="nav-item"><%= link_to "マイページ", customers_mypage_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "カート", cart_items_path, class: "nav-link btn btn-outline mx-1" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link btn btn-outline mx-1" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link btn btn-outline mx-3" %></li>
          <li class="nav-item"><%= link_to "商品一覧", items_path, class: "nav-link btn btn-outline mx-3" %></li>
          <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "nav-link btn btn-outline mx-3" %></li>
          <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "nav-link btn btn-outline mx-3" %></li>
        <% end %>
      </ul>
    </div>
    <div class="header-inner">
      <form>
        <input type="text" placeholder="検索">
        <button>🔍</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANO-CAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>